filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            or:
              - contains:
                  docker.container.name: kafka
              - contains:
                  docker.container.name: postgres
              - contains:
                  docker.container.name: redis
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              multiline.pattern: '^[[:space:]]+(at|\.{3}|Caused by)'
              multiline.negate: false
              multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

logging.level: warning
