spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:task_tracker}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_secret_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094,localhost:9095,localhost:9096}
    producer:
      acks: all
      retries: 2147483647
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        max.in.flight.requests.per.connection: 5
        request.timeout.ms: 30000
        spring.json.add.type.headers: false

app:
  cache:
    redis-enabled: ${REDIS_CACHE_ENABLED:true}
  kafka:
    topic:
      task-notifications: ${TASK_NOTIFICATIONS_TOPIC:task-notifications}
      partitions: ${KAFKA_TOPIC_PARTITIONS:3}
      replication-factor: ${KAFKA_TOPIC_REPLICATION_FACTOR:3}
      min-insync-replicas: ${KAFKA_TOPIC_MIN_INSYNC_REPLICAS:2}

logging:
  level:
    com.example.tasktracker: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: task-service
