input {
  tcp {
    port => 5000
    codec => json_lines
    tags => ["app"]
  }
  beats {
    port => 5044
    tags => ["infra"]
  }
}

filter {
  if "app" in [tags] {
    if ![service_name] {
      mutate { add_field => { "service_name" => "unknown-service" } }
    }
    mutate { add_field => { "log_source" => "application" } }
  }
  if "infra" in [tags] {
    mutate { add_field => { "log_source" => "infrastructure" } }
  }
}

output {
  if "app" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "%{[service_name]}-%{+YYYY.MM.dd}"
    }
  }
  if "infra" in [tags] {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "infra-%{+YYYY.MM.dd}"
    }
  }
}
